root = "." # The root directory of the project
tmp_dir = "tmp" # Temporary directory where air will store its temporary files

[build] # the build configuration
    bin = "main" #the name of the binary file to be generated after building the project
    cmd = "go build -o {{.Output}} {{.Input}}" # the command to build the project
    exclude = ["tmp/*", "client/*"] # specifies the directories to be excluded from monitoring for changes
    include = ["**/*.go"] # specifies the file patterns to be included for monitoring
    ignore = ["tmp/*"] # specifies the files or directories to be ignored when triggering a build